### PR TITLE
Search Engine Optimisation (SEO) for Pages

### PR DESCRIPTION
**Pull request by gburton**
Very simple and touches no core code.  Would be used for pages such as specials, whats_new and so on, as well as the base index.php.

It would not be used for dynamic pages such as index.php (categories), index.php (manufacturers), product_info.php.  These will have their own modules.

### CODE REVIEW

**Comment by skleiner** [comment]
Do you need any testing on these?

**Comment by gburton** [comment]
If you have time, yes please Steve. Thank You

**Comment by skleiner** [comment]
Index:
head title : Index Page Title, seo mods test shop (36 characters)
description : This is the description of your site to be used in the META Description Element (79 characters)
keywords : these, are, the, comma, separated, keywords, used in the META keywords Element ( 7 items )
specials:
head title : Special Offers Page, seo mods test shop (39 characters)
description : Specials Description (20 characters)
keywords : special offers, reduced prices ( 2 items )

**Comment by skleiner** [comment]
I don't know if it's a big deal or now but what do you think about a pipe | as opposed to a comma , in the head title between the page title and the shop name?

**Comment by gburton** [comment]
I dont know...is there any known difference between the two ?

**Comment by skleiner** [comment]
Googled the topic

The comma uses less space if that's a concern on SEO results 

product, shop name
product | shop name

Seems for the human reader, the pipe makes a clearer distinction on the SERP

Vintage 1970 VW Beetle, Fred's Car World
Vintage 1970 VW Beetle | Fred's Car World

I couldn't find anything definitive what google search engines think about this but moz seems to like the pipe

**Comment by gburton** [comment]
How about; https://github.com/gburton/osCommerce-234-bootstrap/commit/774a9f12e60560a68193c6a6024995c3737755eb

**Comment by skleiner** [comment]
Looks good and the idea of letting the shop owner decide is the way to go.  Will test in a day or so.

**Pull request merged**
